BEGIN;

CREATE TABLE IF NOT EXISTS public.bolsistas
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cpf character varying(255) COLLATE pg_catalog."default" NOT NULL,
    data_nascimento date,
    nome_completo character varying(255) COLLATE pg_catalog."default",
    necessidades boolean,
    raca_cor character varying(255) COLLATE pg_catalog."default",
    cliente_id integer,
    CONSTRAINT bolsistas_pkey PRIMARY KEY (id),
    CONSTRAINT ukps1dt4m8htty0ttwwc5jfy6av UNIQUE (cpf)
);

END;