BEGIN;

CREATE TABLE IF NOT EXISTS public.clientes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cpf character varying(255) COLLATE pg_catalog."default",
    data_nascimento date,
    email character varying(255) COLLATE pg_catalog."default",
    nome_completo character varying(255) COLLATE pg_catalog."default",
    telefone character varying(255) COLLATE pg_catalog."default",
    status boolean,
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT clientes_pkey PRIMARY KEY (id),
    CONSTRAINT uk7wflw78ibh162cmq12ii6ffly UNIQUE (cpf)
);

END;