BEGIN;

CREATE TABLE IF NOT EXISTS public.cursos
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    desconto_entrada numeric(38, 2),
    valor_desconto numeric(38, 2),
    imagem_url character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    valor_original numeric(38, 2),
    bolsa_percentual numeric(38, 2),
    turno character varying(255) COLLATE pg_catalog."default",
    status boolean,
    vagas integer,
    instituicao_id integer,
    CONSTRAINT cursos_pkey PRIMARY KEY (id)
);

END;