BEGIN;

CREATE TABLE IF NOT EXISTS public.inscricoes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    data_inscricao date,
    status character varying(255) COLLATE pg_catalog."default",
    curso_id integer NOT NULL,
    bolsista_id integer NOT NULL,
    CONSTRAINT inscricoes_pkey PRIMARY KEY (id)
);

END;